# Generated by Django 5.2.4 on 2025-07-22 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(choices=[('Mercedes Benz', 'Mercedes Benz'), ('Toyota', 'Toyota'), ('Tesla', 'Tesla'), ('Hyundai', 'Hyundai'), ('Volkswagen', 'Volkswagen'), ('Audi', 'Audi'), ('BMW', 'BMW')], max_length=50, verbose_name='Marca')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('lugares', models.IntegerField(verbose_name='Número de Lugares')),
                ('transmissao', models.CharField(choices=[('AT', 'Automática'), ('MT', 'Manual'), ('AUTO', 'Automática')], max_length=10, verbose_name='Transmissão')),
                ('combustivel', models.CharField(choices=[('Petrol', 'Gasolina'), ('Electric', 'Elétrico'), ('Diesel', 'Diesel')], max_length=20, verbose_name='Combustível')),
                ('quilometragem', models.IntegerField(verbose_name='Quilometragem (KM)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Imagem do Carro')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Venda')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Final da Venda')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Carro Vendido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.customer', verbose_name='Comprador')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
