# Generated by Django 5.2.4 on 2025-07-23 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status_veiculo',
            field=models.CharField(choices=[('Disponível', 'Disponível para Venda'), ('Em Vistoria', 'Em Vistoria'), ('Em Lavagem', 'Em Lavagem'), ('Reservado', 'Reservado'), ('Vendido', 'Vendido'), ('Manutenção', 'Em Manutenção')], default='Disponível', max_length=20, verbose_name='Status do Veículo'),
        ),
        migrations.CreateModel(
            name='Lavagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lavagem', models.DateField(verbose_name='Data da Lavagem')),
                ('tipo_lavagem', models.CharField(choices=[('Simples', 'Lavagem Simples'), ('Completa', 'Lavagem Completa'), ('Detalhada', 'Lavagem Detalhada'), ('Polimento', 'Polimento')], max_length=20, verbose_name='Tipo de Lavagem')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Custo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Carro')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Lavagem',
                'verbose_name_plural': 'Lavagens',
                'ordering': ['-data_lavagem'],
            },
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vistoria', models.DateField(verbose_name='Data da Vistoria')),
                ('resultado', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente')], default='Pendente', max_length=20, verbose_name='Resultado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Carro')),
                ('vistoriador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vistoriador')),
            ],
            options={
                'verbose_name': 'Vistoria',
                'verbose_name_plural': 'Vistorias',
                'ordering': ['-data_vistoria'],
            },
        ),
    ]
