# Generated by Django 5.2.4 on 2025-07-23 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_status_veiculo_lavagem_vistoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carros_vendidos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Responsável'),
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Novo Contato', 'Novo Contato'), ('Em Andamento', 'Em Andamento (Tirando Dúvidas)'), ('Negociação', 'Negociação'), ('Aguardando Resposta', 'Aguardando Resposta do Cliente'), ('Fechado - Ganho', 'Fechado - Venda Concluída'), ('Fechado - Perdido', 'Fechado - Venda Perdida'), ('Follow-up', 'Follow-up Necessário')], default='Novo Contato', max_length=50, verbose_name='Status da Interação')),
                ('data_interacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Interação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Notas da Interação')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Carro de Interesse')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.customer', verbose_name='Cliente/Lead')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Responsável')),
            ],
            options={
                'verbose_name': 'Interação de Lead',
                'verbose_name_plural': 'Interações de Leads',
                'ordering': ['-ultima_atualizacao'],
            },
        ),
    ]
