# Generated by Django 5.2.4 on 2025-07-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_leadinteraction_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='status',
            field=models.CharField(choices=[('Novo Contato', 'Novo Contato'), ('Em Andamento', 'Em Andamento (Tirando Dúvidas)'), ('Negociação', 'Negociação'), ('Aguardando Resposta', 'Aguardando Resposta do Cliente'), ('Fechado - Ganho', 'Fechado - Venda Concluída'), ('Fechado - Perdido', 'Fechado - Venda Perdida'), ('Follow-up', 'Follow-up Necessário'), ('Em Andamento (WhatsApp)', 'Em Andamento (WhatsApp)')], default='Novo Contato', max_length=50, verbose_name='Status da Interação'),
        ),
    ]
