# Generated by Django 5.2.4 on 2025-07-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_customer_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lavagem',
            options={'ordering': ['-data_lavagem'], 'permissions': [('can_add_lavagem', 'Pode adicionar lavagem'), ('can_change_lavagem', 'Pode editar lavagem')], 'verbose_name': 'Lavagem', 'verbose_name_plural': 'Lavagens'},
        ),
        migrations.AlterModelOptions(
            name='vistoria',
            options={'ordering': ['-data_vistoria'], 'permissions': [('can_add_vistoria', 'Pode adicionar vistoria'), ('can_change_vistoria', 'Pode editar vistoria')], 'verbose_name': 'Vistoria', 'verbose_name_plural': 'Vistorias'},
        ),
    ]
