# Generated by Django 5.2.4 on 2025-07-28 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_lavagem_options_alter_vistoria_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistoriaPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Padrão')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Padrão de Vistoria',
                'verbose_name_plural': 'Padrões de Vistoria',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='vistoria',
            options={'ordering': ['-data_vistoria'], 'permissions': [('can_add_vistoria', 'Pode adicionar vistoria'), ('can_change_vistoria', 'Pode editar vistoria'), ('can_view_all_vistorias', 'Pode visualizar todas as vistorias')], 'verbose_name': 'Vistoria', 'verbose_name_plural': 'Vistorias'},
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='vistoria',
            name='observacoes_gerais',
            field=models.TextField(blank=True, verbose_name='Observações Gerais'),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='resultado',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente'), ('Finalizada', 'Finalizada')], default='Pendente', max_length=20, verbose_name='Resultado Geral'),
        ),
        migrations.CreateModel(
            name='VistoriaItemPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do Item')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('requires_photo', models.BooleanField(default=False, verbose_name='Requer Foto')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cars.vistoriapattern', verbose_name='Padrão de Vistoria')),
            ],
            options={
                'verbose_name': 'Item do Padrão de Vistoria',
                'verbose_name_plural': 'Itens do Padrão de Vistoria',
                'ordering': ['pattern', 'order'],
                'unique_together': {('pattern', 'description')},
            },
        ),
        migrations.AddField(
            model_name='vistoria',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.vistoriapattern', verbose_name='Padrão de Vistoria Utilizado'),
        ),
        migrations.CreateModel(
            name='VistoriaActualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ok', models.BooleanField(default=True, verbose_name='Está OK?')),
                ('description_result', models.TextField(blank=True, verbose_name='Descrição do Resultado')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vistorias/itens/', verbose_name='Foto do Item')),
                ('vistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_items', to='cars.vistoria', verbose_name='Vistoria')),
                ('item_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vistoriaitempattern', verbose_name='Item do Padrão')),
            ],
            options={
                'verbose_name': 'Item da Vistoria Real',
                'verbose_name_plural': 'Itens da Vistoria Real',
                'ordering': ['item_pattern__order'],
                'unique_together': {('vistoria', 'item_pattern')},
            },
        ),
    ]
