# Generated by Django 5.2.4 on 2025-07-30 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_vistoriapattern_alter_vistoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinteraction',
            name='data_conversao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Conversão'),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='status',
            field=models.CharField(default='Novo Contato', max_length=50, verbose_name='Status da Interação'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='data_venda',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Venda'),
        ),
    ]
