# Generated by Django 5.2.4 on 2025-07-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_leadinteraction_data_conversao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinteraction',
            name='status',
            field=models.CharField(choices=[('Novo Contato', 'Novo Contato'), ('Em Andamento', 'Em Andamento (Tirando Dúvidas)'), ('Negociação', 'Negociação'), ('Aguardando Resposta', 'Aguardando Resposta do Cliente'), ('Fechado - Ganho', 'Fechado - Venda Concluída'), ('Fechado - Perdido', 'Fechado - Venda Perdida'), ('Follow-up', 'Follow-up Necessário'), ('Em Andamento (WhatsApp)', 'Em Andamento (WhatsApp)')], default='Novo Contato', max_length=50, verbose_name='Status da Interação'),
        ),
    ]
